Hw02 express
IhorMal/nodejs-homework-api pull request #1
Opened 2023-01-21 23:43 UTC by IhorMal

2023-01-22 09:53 UTC, Eastvarga requested changes
Є зауваження

2023-01-22 09:53 UTC, Eastvarga commented on models/contacts.js
> +  const json = await readContacts()
не використовуйте не зрозумілі імена для змінних - в данному випадку ви отримуєте contacts

2023-01-22 09:53 UTC, Eastvarga commented on models/contacts.js
> +  const dalet = json.splice(id, 1);
removedContact

2023-01-22 09:53 UTC, Eastvarga commented on models/contacts.js
> +  const schema = Joi.object({
чому валідація не винисена у мідлвар? Треба винести валідацію у мідлвар до виконання цієї функції

2023-01-22 09:53 UTC, Eastvarga commented on models/contacts.js
> +  json.forEach(element => {
є метод масиву map котрий повертає новий масив зформований в залежності від того що поверне калбек функція - тут не потрібен форіч - Вам не казали що мутацій масивів даних треба уникати

2023-01-22 09:53 UTC, Eastvarga commented on server.js
>  app.listen(3000, () => {
чому не має змінної середовища? Вчіться використовувати конфігураційні файли та змінні
const PORT = process.env.PORT || 3000;

2023-01-22 18:55 UTC, Eastvarga requested changes
Є зауваження, треба їх виправити

2023-01-22 18:55 UTC, Eastvarga commented on middlewares/middlewaresValidation.js
> +            res.json({"message": "missing required name field"})
тут повинна виводитись помилка валідаціі - "немає поля пошти" або "невірне поле пошти" подивіться що повертає  schema.validate(req.body);
це дивний запис
            res.status(400);
            res.json({"message": "missing required name field"})
            це можна записати так
 res.status(400).json({"message": "missing required name field"})

2023-01-22 18:55 UTC, Eastvarga commented on middlewares/middlewaresValidation.js
> +            return false
чому не виводите помилку валідаціїї?

2023-01-22 18:55 UTC, Eastvarga commented on models/contacts.js
> +  const removedContact = contacts.splice(id, 1);
хіба Вас не вчили не використовувати логіку, котра мутує дані масивів? Поки не критично, однак це важливо надалі

2023-01-22 18:55 UTC, Eastvarga commented on routes/api/contacts.js
> +  res.json({list})
res.status(200).json(list) може так більш доцільніше? Або вже хочаб так res.status(200).json({ data })

2023-01-22 18:55 UTC, Eastvarga commented on routes/api/contacts.js
> +  res.json({...itemAdd})
це не потрібно якщо зробити так res.status(200).json(itemAdd)

2023-01-22 18:55 UTC, Eastvarga commented on server.js
> +app.use('/api/contacts', routerApi);
А що це за дублювання? з чого це Ви вирішили код app скопіювати? не потрібно це тут

2023-01-22 21:15 UTC, Eastvarga requested changes
Є зауваження.

2023-01-22 21:15 UTC, Eastvarga commented on middlewares/middlewaresValidation.js
>              return
Ось це не потрібно - ця логіка є у валідаторі якщо у схемі було вказано що поле  required

2023-01-22 21:15 UTC, Eastvarga commented on middlewares/middlewaresValidation.js
>            const contact = schema.validate(res.body);
Ось тут Ви валідуєте res.body відносно вашої схеми - отже Ваше завданя створити вірно схему, а потім її провалідувати - якщо вона не валідна вам повернеться помилка відповідна.

2023-01-22 21:15 UTC, Eastvarga commented on models/contacts.js
> +  const filterContacts = contacts.filter((element, index)=> index !== id)
Не плутайте індекс елементу у масиві з полем id елементу - index !== id це невірно
let deletedIndex;
const filterContacts = contacts.filter((element, index)=>{ 
if(element.id=== id){
deletedIndex =index
} 
return element.id!= id})

return contacts[deletedIndex]
спробуйте розібратись, що тут до чого, та використати

2023-01-22 21:29 UTC, IhorMal commented on middlewares/middlewaresValidation.js
>              return
якраз в мене і не має required тому що я оновлю контакт і знання може прийти тільки одне

2023-01-22 21:35 UTC, Eastvarga commented on middlewares/middlewaresValidation.js
>              return
Optional - якщо вірно пам'ятаю це в схемі помічає поле як опціональне.

2023-01-22 21:48 UTC, IhorMal commented on models/contacts.js
> +  const filterContacts = contacts.filter((element, index)=> index !== id)
`
  const id = contacts.findIndex(element => String(contactId) === element.id)
  if (id === -1) {
    return null
  }
  const filterContacts = contacts.filter((element, index)=> index !== id)
`

я зназоджу індекс верху за допомогою findIndex а потім пропускаю його через filter

2023-01-22 21:59 UTC, IhorMal commented on middlewares/middlewaresValidation.js
>            const contact = schema.validate(res.body);
`const schema = Joi.object({
            name: Joi.string()
                  .optional(),
            email: Joi.string()
                  .email({ minDomainSegments: 2, tlds: { allow: ['com', 'net'] } })
                  .optional(),
            phone : Joi.string()
                  .optional(),
                  
          });
const contact = schema.validate(res.body);
`
схема є вона находиця вище

2023-01-22 22:09 UTC, IhorMal commented on middlewares/middlewaresValidation.js
>              return
Optional - позначає ключ як необов’язковий. Використовується для анотації схеми для зручності читання
Якщо body немає, повертає json з ключем {"message": "missing fields"} і статусом 400
Я просто не міг найти в joi перевірку на пустий масив

2023-01-22 22:12 UTC, IhorMal commented on models/contacts.js
> +  const filterContacts = contacts.filter((element, index)=> index !== id)
я не шукав id я найшов index і потім переправ по ньому масив

2023-01-22 22:15 UTC, IhorMal commented on models/contacts.js
> +  const filterContacts = contacts.filter((element, index)=> index !== id)
все добре працює перевіряв

2023-01-22 22:37 UTC, IhorMal commented on models/contacts.js
> +  const filterContacts = contacts.filter((element, index)=> index !== id)
я просто переміну погано написав яка шукає індекс замість id мав написати index я вже виправив

2023-01-23 18:05 UTC, Eastvarga commented on models/contacts.js
> +  const filterContacts = contacts.filter((element, index)=> index !== id)
Добре, але Ви двічі пройшлися по масиву для дії яка може бути виконана при одному проході по масиву, не будете зважати на таке, Вам же гірше. В програмуванні головне знаходити оптимальні рішення, з мінімумом ресурсів (час виконання, пам'ять) робити необхідні дії,

2023-01-23 18:07 UTC, Eastvarga commented on middlewares/middlewaresValidation.js
>            const contact = schema.validate(res.body);
validationUpdateContact: (req, res, next) => {
        const schema = Joi.object({
            name: Joi.string()
                  .optional(),
                
            email: Joi.string()
                  .email({ minDomainSegments: 2, tlds: { allow: ['com', 'net'] } })
                  .optional(),
            phone : Joi.string()
                  .optional(),
                  
          })**.min(1)**;
        
          const contact = schema.validate(req.body);
          
          if (contact.error) {
            const error = contact.error.details[0].message;
             res.status(400).json({"message": `${error.replace(/[^a-zа-яё0-9\s]/gi)}`})
             return
          }
          
          next()  
    }
    
    Достатньо вказати мінімум (**.min(1)**) кількість необхідних полів (документація джой) 
    та не робити зайві  дії -
    if (Object.keys(req.body).length === 0) {
            res.status(400).json({ "message": "missing fields"})
            return
        }

2023-01-23 18:09 UTC, Eastvarga approved these changes
Є коментарі, 
головний - шукайте оптимальну логіку для поточних Ваших цілей.

2023-01-23 18:09 UTC, merged

2023-01-23 18:46 UTC, IhorMal commented on models/contacts.js
> +  const filterContacts = contacts.filter((element, index)=> index !== id)
дякую скористаюсь вашою порадою

2023-01-23 18:47 UTC, IhorMal commented on middlewares/middlewaresValidation.js
>            const contact = schema.validate(res.body);
Добре